// src/components/navbar.tsx
import { Link } from "@tanstack/react-router"
import { useTheme } from "next-themes"
import { Moon, Printer, Sun, X } from "lucide-react"
import { useState } from "react"

export function Navbar() {
    const { theme, setTheme } = useTheme()
    const [isPrintMode, setIsPrintMode] = useState(false)

    const toggleTheme = () => {
        setTheme(theme === "dark" ? "light" : "dark")
    }

    const togglePrintMode = () => {
        setIsPrintMode(!isPrintMode)
        // You could add print mode logic here
    }

    return (
        <nav className="w-full border-b border-[#d8dee4] px-4 py-2 shadow-sm dark:border-[#21262d]">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                {/* Top: Logo and Navigation */}
                <div className="flex w-full flex-col items-center gap-2 sm:flex-row sm:gap-8">
                    <Link to="/" className="flex items-center">
                        <img
                            src="/the_corner-logo.webp"
                            alt="The Corner Logo"
                            className="h-10 w-auto min-w-[40px] dark:invert"
                        />
                    </Link>
                    <div className="mt-2 flex items-center gap-2 sm:mt-0 sm:gap-4">
                        <Link
                            to="/folders"
                            activeProps={{
                                className:
                                    "border-b-2 border-[#0969da] dark:border-[#2f81f7] text-[#24292f] dark:text-[#f0f6fc] font-semibold"
                            }}
                            inactiveProps={{
                                className:
                                    "border-b-2 border-transparent text-[#57606a] dark:text-[#8b949e] hover:text-[#24292f] dark:hover:text-[#f0f6fc]"
                            }}
                            className="px-2 py-1 transition-colors"
                        >
                            Folders
                        </Link>
                        <Link
                            to="/issues"
                            activeProps={{
                                className:
                                    "border-b-2 border-[#0969da] dark:border-[#2f81f7] text-[#24292f] dark:text-[#f0f6fc] font-semibold"
                            }}
                            inactiveProps={{
                                className:
                                    "border-b-2 border-transparent text-[#57606a] dark:text-[#8b949e] hover:text-[#24292f] dark:hover:text-[#f0f6fc]"
                            }}
                            className="px-2 py-1 transition-colors"
                        >
                            Issues
                        </Link>
                    </div>
                </div>

                <div className="flex w-full items-center gap-4 sm:w-auto">
                    <button
                        type="button"
                        className="inline-flex h-10 w-10 items-center justify-center rounded-md hover:bg-accent"
                        aria-label="Print page"
                        onClick={togglePrintMode}
                    >
                        {!isPrintMode ? (
                            <Printer className="h-5 w-5" />
                        ) : (
                            <X className="h-5 w-5" />
                        )}
                    </button>

                    <button
                        type="button"
                        onClick={toggleTheme}
                        className="inline-flex h-10 w-10 items-center justify-center rounded-md hover:bg-accent"
                        aria-label="Toggle color scheme"
                    >
                        {theme === "dark" ? (
                            <Sun className="h-5 w-5" />
                        ) : (
                            <Moon className="h-5 w-5" />
                        )}
                    </button>

                    <a
                        href="https://github.com/the-corner-inc/structures"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex h-10 w-10 items-center justify-center rounded-md hover:bg-accent"
                        aria-label="View on GitHub"
                    >
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="h-5 w-5"
                        >
                            <path
                                fillRule="evenodd"
                                d="M12 2C6.477 2 2 6.484 2 12.021c0 4.428 2.865 8.184 6.839 9.504.5.092.682-.217.682-.482 0-.237-.009-.868-.014-1.703-2.782.605-3.369-1.342-3.369-1.342-.454-1.157-1.11-1.465-1.11-1.465-.908-.62.069-.608.069-.608 1.004.07 1.532 1.032 1.532 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.339-2.221-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.025A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.295 2.748-1.025 2.748-1.025.546 1.378.202 2.397.1 2.65.64.7 1.028 1.595 1.028 2.688 0 3.847-2.337 4.695-4.566 4.944.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.744 0 .267.18.577.688.48C19.138 20.2 22 16.447 22 12.021 22 6.484 17.523 2 12 2Z"
                                clipRule="evenodd"
                            />
                        </svg>
                    </a>
                </div>
            </div>
        </nav>
    )
}

// src/app/navbar/navbar.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'struct-navbar',
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavbarComponent {}

<nav
  class="w-full shadow-sm border-b border-[#d8dee4] dark:border-[#21262d] px-4 py-2 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"
>
  <!-- Top: Logo and Navigation -->
  <div class="flex flex-col sm:flex-row items-center gap-2 sm:gap-8 w-full">
    <a routerLink="/" class="flex items-center">
      <img
        src="/the_corner-logo.webp"
        alt="The Corner Logo"
        class="h-10 w-auto min-w-[40px] dark:invert-100"
      />
    </a>
    <div class="flex items-center gap-2 sm:gap-4 mt-2 sm:mt-0">
      <a
        routerLink="/folders"
        routerLinkActive="border-b-2 border-[#0969da] dark:border-[#2f81f7] text-[#24292f] dark:text-[#f0f6fc] font-semibold"
        class="px-2 py-1 border-b-2 border-transparent text-[#57606a] dark:text-[#8b949e] hover:text-[#24292f] dark:hover:text-[#f0f6fc] transition-colors"
        >Folders</a
      >
      <a
        routerLink="/issues"
        routerLinkActive="border-b-2 border-[#0969da] dark:border-[#2f81f7] text-[#24292f] dark:text-[#f0f6fc] font-semibold"
        class="px-2 py-1 border-b-2 border-transparent text-[#57606a] dark:text-[#8b949e] hover:text-[#24292f] dark:hover:text-[#f0f6fc] transition-colors"
        >Issues</a
      >
    </div>
  </div>

  <div class="flex items-center gap-4 w-full sm:w-auto">
    <button
      type="button"
      class="icon-button"
      aria-label="Print page"
      (click)="isPrintMode.next(!isPrintMode$())"
    >
      @if (!isPrintMode$()) {
        <svg
          class="w-6 h-6 text-gray-800 dark:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          fill="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            fill-rule="evenodd"
            d="M8 3a2 2 0 0 0-2 2v3h12V5a2 2 0 0 0-2-2H8Zm-3 7a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h1v-4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v4h1a2 2 0 0 0 2-2v-5a2 2 0 0 0-2-2H5Zm4 11a1 1 0 0 1-1-1v-4h8v4a1 1 0 0 1-1 1H9Z"
            clip-rule="evenodd"
          />
        </svg>
      } @else {
        <svg
          class="w-6 h-6 text-gray-800 dark:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          fill="none"
          viewBox="0 0 24 24"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      }
    </button>

    <button
      type="button"
      (click)="toggleScheme()"
      class="icon-button"
      aria-label="Toggle color scheme"
    >
      @if ($darkMode()) {
        <svg
          class="w-6 h-6 text-gray-800 dark:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          fill="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            fill-rule="evenodd"
            d="M13 3a1 1 0 1 0-2 0v2a1 1 0 1 0 2 0V3ZM6.343 4.929A1 1 0 0 0 4.93 6.343l1.414 1.414a1 1 0 0 0 1.414-1.414L6.343 4.929Zm12.728 1.414a1 1 0 0 0-1.414-1.414l-1.414 1.414a1 1 0 0 0 1.414 1.414l1.414-1.414ZM12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10Zm-9 4a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2H3Zm16 0a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2h-2ZM7.757 17.657a1 1 0 1 0-1.414-1.414l-1.414 1.414a1 1 0 1 0 1.414 1.414l1.414-1.414Zm9.9-1.414a1 1 0 0 0-1.414 1.414l1.414 1.414a1 1 0 0 0 1.414-1.414l-1.414-1.414ZM13 19a1 1 0 1 0-2 0v2a1 1 0 1 0 2 0v-2Z"
            clip-rule="evenodd"
          />
        </svg>
      } @else {
        <svg
          class="w-6 h-6 text-gray-800 dark:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          fill="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            fill-rule="evenodd"
            d="M11.675 2.015a.998.998 0 0 0-.403.011C6.09 2.4 2 6.722 2 12c0 5.523 4.477 10 10 10 4.356 0 8.058-2.784 9.43-6.667a1 1 0 0 0-1.02-1.33c-.08.006-.105.005-.127.005h-.001l-.028-.002A5.227 5.227 0 0 0 20 14a8 8 0 0 1-8-8c0-.952.121-1.752.404-2.558a.996.996 0 0 0 .096-.428V3a1 1 0 0 0-.825-.985Z"
            clip-rule="evenodd"
          />
        </svg>
      }
    </button>

    <a
      href="https://github.com/the-corner-inc/structures"
      target="_blank"
      rel="noopener noreferrer"
      class="icon-button"
      aria-label="View on GitHub"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        class="w-6 h-6 text-gray-800 dark:text-white"
      >
        <path
          fill-rule="evenodd"
          d="M12 2C6.477 2 2 6.484 2 12.021c0 4.428 2.865 8.184 6.839 9.504.5.092.682-.217.682-.482 0-.237-.009-.868-.014-1.703-2.782.605-3.369-1.342-3.369-1.342-.454-1.157-1.11-1.465-1.11-1.465-.908-.62.069-.608.069-.608 1.004.07 1.532 1.032 1.532 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.339-2.221-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.025A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.295 2.748-1.025 2.748-1.025.546 1.378.202 2.397.1 2.65.64.7 1.028 1.595 1.028 2.688 0 3.847-2.337 4.695-4.566 4.944.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.744 0 .267.18.577.688.48C19.138 20.2 22 16.447 22 12.021 22 6.484 17.523 2 12 2Z"
          clip-rule="evenodd"
        />
      </svg>
    </a>
  </div>
</nav>
